version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  backend:
    image: node:latest
    ports:
      - 5000:5000
    volumes:
      - ./packages/back:/api
    working_dir: /api
    command: make init
    depends_on:
      - mongo
    environment:
      - DB_LOGIN=adam
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_SCHEMA=meh
      - HASH="123ewer09LKJDFIJU"

  frontend:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./packages/front:/app
    working_dir: /app
    command: make init




